name: Linter
on:
  pull_request:
    branches:
      - develop
      - release**
  merge_group:
    branches:
      - develop
      - release**
  push:
    branches:
      - develop
      - release**

# No permissions by default, no specific permissions are required for this workflow
permissions: {}
jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10"

      # Install pre-commit
      - name: Install pre-commit
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install prek

      # Execute pre-commit checks
      - name: Run pre-commit checks
        shell: bash
        run: prek run --all-files

  Zizmor-Scan-PR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run Zizmor scan
        uses: open-edge-platform/geti-ci/actions/zizmor@3a4b81ea648711eb638b34757427cd3ef71d19f1
        with:
          scan-scope: "changed"
          severity-level: "LOW"
          confidence-level: "LOW"
          fail-on-findings: true
  Bandit-Scan-PR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run Bandit scan
        uses: open-edge-platform/geti-ci/actions/bandit@3a4b81ea648711eb638b34757427cd3ef71d19f1
        with:
          scan-scope: "changed"
          severity-level: "LOW"
          confidence-level: "LOW"
          config_file: "pyproject.toml"
          fail-on-findings: true
