name: Weekly Stability Test
on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    # every 7PM on Sunday
    - cron: "0 19 * * 0"

# No permissions by default, no specific permissions are required for this workflow
permissions: {}

# This is what will cancel the workflow concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  weekly_stability_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        extra: ["default", "tf", "tfds", "torch"]
        include:
          - python-version: "3.9"
            tox-env-py: "39"
          - python-version: "3.10"
            tox-env-py: "310"
          - python-version: "3.11"
            tox-env-py: "311"
    name: stability test (Python ${{ matrix.python-version }}, Extra ${{ matrix.extra }})
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Installing python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install tox
      - name: Stability testing
        run: |
          tox -e stability-${{ matrix.extra }}
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: stability-${{ matrix.python-version }}-${{ matrix.extra }}
          path: .tox/stability-${{ matrix.extra }}/log
  call-notify-to-teams:
    needs: [weekly_stability_test]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: ./.github/workflows/notify_teams.yml
    secrets:
      MSTEAMS_WEBHOOK: ${{ secrets.MSTEAMS_WEBHOOK }}
